### ISSUE TITLE
The update check fails

### ISSUE THREAD

**Issue by frase-git** [cmb69/polyglott_xh#18]
The headline says it all.

**Comment by cmb69** [comment]
Indeed, <http://3-magi.net/downloads/versioninfo/polyglott1.nfo> gives 503. I'll fix this as soon as possible.

**Comment by frase-git** [comment]
Take it easy.
;-)

**Comment by cmb69** [comment]
Should be fixed now.

**Comment by frase-git** [comment]
That was fast.
Thank you!
