### ISSUE TITLE
Incorrect version in download?

### ISSUE THREAD

**Issue by frase-git** [cmb69/polyglott_xh#19]
After some attempts I had to find out that all here downloadable versions do not work.
See here: https://cmsimpleforum.com/viewtopic.php?f=12&t=15498&p=72909#p72909
The old version I still have works fine.

**Comment by cmb69** [comment]
Indeed, that repo only offered the sources; I have just uploaded the Polyglott_XH-1.0beta2.zip
release package. Thanks for notification!
